#! /bin/sh

# autostart

pgrep -x sxhkd > /dev/null || sxhkd &
exec picom  &

killall -q polybar &

nitrogen --restore &
# $HOME/.config/polybar/launch.sh &
bspc monitor -d I II III IV V VI VII



if [[ $(xrandr -q | grep "DP-1 connected 1") ]]; then
  xrandr --output 'DP-1' --primary --mode 1920x1080 --rotate normal --rate 74.97 --output 'eDP-1' --off &
  bspc "DP-1" -d I II III IV V VI VII & 
  bspc config bottom_padding 120 &
  polybar taskbar_ext_detached &
else
  xrandr --output 'eDP-1' --primary --mode 1920x1200 --rotate normal &
  bspc "eDP-1" -d I II III IV V VI VII &
  bspc config bottom_padding 0 &
  polybar taskbar &
fi

# config

bspc config border_width         2
bspc config window_gap           5
bspc config top_padding		      40
# bspc config border_radius 	  0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colors

bspc config normal_border_color		"#11111B"
bspc config active_border_color		"#11111B"
bspc config focused_border_color	"#005ca1"
bspc config presel_feedback_color	"#005ca1"

# rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser-nightly desktop='^4' state=tiling follow=on
bspc rule -a "spotify" dekstop='^6' state=tiling follow=on
bspc rule -a "Microsoft Teams - Preview" desktop='^5' state=tiling follow=on
bspc rule -a "obsidian" desktop='^3' state=tiling follow=on 
